"""baseline schema marker (tables already created via create_all + lightweight migrations)

Revision ID: 20260729_0001
Revises:
Create Date: 2026-07-29

This revision is a no-op stamp so production can adopt Alembic without rebuilding
the existing SQLite file. New schema changes should be autogenerated revisions
stacked on this baseline.
"""
from typing import Sequence, Union

from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401

revision: str = "20260729_0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Baseline: schema is owned by SQLAlchemy models + database.init_db()
    # lightweight ADD COLUMN for existing DBs. Future revisions mutate schema.
    pass


def downgrade() -> None:
    pass
