#!/usr/bin/env python3
"""Check vernacular completeness; emit missing_vernaculars.yaml (PR-07b)."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "data" / "species_catalog" / "species_catalog_v2.json"
OUT_YAML = ROOT / "data" / "species_catalog" / "missing_vernaculars.yaml"
LOCALES = ("es", "ca", "eu", "en")


def main() -> int:
    if not CATALOG.exists():
        print("catalog missing", file=sys.stderr)
        return 1
    data = json.loads(CATALOG.read_text(encoding="utf-8"))
    missing: list[dict] = []
    hard_fail = 0
    for sp in data.get("species", []):
        vern = sp.get("vernacular_names") or {}
        miss_locs = [loc for loc in LOCALES if not vern.get(loc)]
        if not miss_locs:
            continue
        entry = {
            "scientific_name": sp["scientific_name"],
            "slug": sp["slug"],
            "risk_level": sp.get("risk_level"),
            "missing_locales": miss_locs,
        }
        missing.append(entry)
        if sp.get("risk_level") in ("deadly", "high") or sp.get("edibility_code") in (
            "mortifero",
            "toxico",
        ):
            hard_fail += 1
            print("FAIL deadly/high missing:", sp["scientific_name"], miss_locs)

    # Write simple YAML without pyyaml dependency
    lines = ["# Generated by scripts/check_i18n_catalog.py", "missing:"]
    if not missing:
        lines.append("  []")
    else:
        for m in missing:
            lines.append(f"  - scientific_name: {m['scientific_name']!r}")
            lines.append(f"    slug: {m['slug']}")
            lines.append(f"    risk_level: {m['risk_level']}")
            lines.append(f"    missing_locales: {m['missing_locales']}")
    OUT_YAML.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_YAML} ({len(missing)} tickets)")
    print(f"Hard fails (deadly/high): {hard_fail}")
    return 1 if hard_fail else 0


if __name__ == "__main__":
    sys.exit(main())
